### ISSUE TITLE
DAMNN BRO STILL MAKING CAM......  but i got crash when i join the server, its says error module or somthn i forgot :) butt W for making this thing work again.. Cant wait for the next update

### ISSUE THREAD

**Issue by V-Rusa** [sp00kY0/293ui1049#1]

**Comment by sp00kY0** [comment]
this cheat is made for latest 32 bit version of the game. If you have crashed, then I need more information about it, if possible, then record a video

**Comment by V-Rusa** [comment]
https://streamable.com/bdbrwx 

here the vid sirr

**Comment by V-Rusa** [comment]
if there any update going on lemme know sir, I would be happy to be the first tester Mwehehee
